version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
      - ./configdb:/data/confiddb

  mongo-espress:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  nextjs:
    build:
      context: .
      dockerfile: DockerfileNextJS
    command: sh -c "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  django:
    build:
      context: .
      dockerfile: DockerfileDjango
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app:cached
    ports:
      - "8000:8000"
    depends_on:
      - mongo
